# Generated by Django 4.2.7 on 2024-01-28 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
